version: '3.8'

services:
  node-server:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - OLLAMA_API_URL=http://ollama:11434/api
    depends_on:
      - ollama
    networks:
      - app-network

  ollama:
    image: ollama/ollama
    ports:
      - "11436:11434"  # Ollama service port mapping
    volumes:
      - ollama_data:/root/.ollama
      - ./init.sh:/usr/local/bin/init.sh
    networks:
      - app-network

volumes:
  ollama_data:

networks:
  app-network:
    driver: bridge
